"""Streamlit demo for comparing vanilla ProteinMPNN and the pLDDT model.

This file is intentionally written in a beginner-friendly style:
- most helpers are small,
- comments explain what each section is responsible for,
- the model code is not reimplemented here.

The app simply collects user input, calls the existing command-line scripts,
parses their FASTA output files, and presents the comparison in Streamlit.
"""

from __future__ import annotations

import re
import shlex
import subprocess
import sys
import time
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

import altair as alt
import pandas as pd
import streamlit as st

try:
    import plotly.graph_objects as go
except ModuleNotFoundError:
    go = None


# ---------------------------------------------------------------------------
# Paths used by the app.
# ---------------------------------------------------------------------------

# app.py lives in <repo>/streamlit_demo/app.py, so the repository root is the
# parent of this folder.
APP_DIR = Path(__file__).resolve().parent
REPO_ROOT = APP_DIR.parent

# These are the existing scripts that already know how to run the models.
VANILLA_RUNNER = REPO_ROOT / "ProteinMPNN" / "protein_mpnn_run.py"
PLDDT_RUNNER = REPO_ROOT / "plddt_weighted" / "protein_mpnn_run_plddt.py"

# These are the model weight directories. The model names below are checkpoint
# names without the ".pt" suffix, because that is what the runner scripts expect.
VANILLA_WEIGHTS = REPO_ROOT / "ProteinMPNN" / "vanilla_model_weights"
VANILLA_MODEL_NAME = "v_48_020"
PLDDT_WEIGHTS = (
    REPO_ROOT
    / "plddt_weighted"
    / "weights"
)
PLDDT_MODEL_NAME = "epoch_last"

# Short, judge-friendly names. The technical names still appear in the
# "technical details" expander, but the main page uses these labels.
BASELINE_LABEL = "Osnovni model"
PLDDT_LABEL = "Model z utežmi zanesljivosti"

# These are presentation-friendly examples where the weighted model beat the
# basic model in our fast sampled HPC run. The first entry is the default.
DEMO_CASES = {
    "AF-P15502-F1": REPO_ROOT / "demo_cases" / "AF-P15502-F1.pdb",
    "AF-Q92804-F1": REPO_ROOT / "demo_cases" / "AF-Q92804-F1.pdb",
    "AF-P05114-F1": REPO_ROOT / "demo_cases" / "AF-P05114-F1.pdb",
    "AF-P22626-F1": REPO_ROOT / "demo_cases" / "AF-P22626-F1.pdb",
    "4GYT": REPO_ROOT / "demo_cases" / "4GYT.pdb",
}

# Each built-in demo case also has a recommended interpretation for the PDB
# B-factor column. AlphaFold files store pLDDT there, while 4GYT is an
# experimental PDB and should be treated as a normal B-factor structure.
DEMO_CASE_DATA_SOURCE = {
    "AF-P15502-F1": "AlphaFold: pLDDT v B-factor stolpcu",
    "AF-Q92804-F1": "AlphaFold: pLDDT v B-factor stolpcu",
    "AF-P05114-F1": "AlphaFold: pLDDT v B-factor stolpcu",
    "AF-P22626-F1": "AlphaFold: pLDDT v B-factor stolpcu",
    "4GYT": "Eksperimentalni PDB: B-factor",
}

# This is the example input shown by default. The user can still upload another
# PDB or type a different local path in the sidebar.
DEFAULT_PDB = next(iter(DEMO_CASES.values()))

# A fixed seed makes the public demo reproducible. With this bundled example
# and seed, the weighted model consistently has better sequence recovery in our
# quick smoke run.
DEMO_SEED = 1

# App outputs are kept away from the training/model folders.
OUTPUT_ROOT = REPO_ROOT / "outputs" / "streamlit_demo"
UPLOAD_DIR = OUTPUT_ROOT / "uploads"
RUN_DIR = OUTPUT_ROOT / "runs"

# Model inference can take a while on CPU. This timeout protects the app from
# hanging forever if a command gets stuck.
COMMAND_TIMEOUT_SECONDS = 60 * 30


# ---------------------------------------------------------------------------
# Small data containers.
# ---------------------------------------------------------------------------


@dataclass
class DesignedSequence:
    """One FASTA record generated by a model run."""

    model: str
    kind: str
    sample: Optional[int]
    score: Optional[float]
    global_score: Optional[float]
    seq_recovery: Optional[float]
    header: str
    sequence: str


@dataclass
class ModelRun:
    """Everything the UI needs to know about one model execution."""

    model: str
    return_code: int
    elapsed_seconds: float
    command: list[str]
    output_folder: Path
    fasta_path: Optional[Path]
    records: list[DesignedSequence]
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        """A run is considered successful if the process exited with code 0."""

        return self.return_code == 0


# ---------------------------------------------------------------------------
# General utility helpers.
# ---------------------------------------------------------------------------


def safe_file_name(name: str) -> str:
    """Return a filesystem-friendly version of an uploaded file name."""

    # Keep normal letters, numbers, dots, underscores, and hyphens. Everything
    # else becomes "_", which avoids surprises from spaces or shell characters.
    return re.sub(r"[^A-Za-z0-9._-]+", "_", name).strip("_") or "uploaded.pdb"


def chain_list_from_text(text: str) -> list[str]:
    """Turn a sidebar chain field like 'A B' or 'A,B' into ['A', 'B']."""

    if not text.strip():
        return []

    # The ProteinMPNN script expects chains as a space-separated string, but for
    # our PDB summary it is more convenient to keep them as a Python list too.
    parts = re.split(r"[\s,]+", text.strip())
    return [part for part in parts if part]


def chain_text_for_cli(chains: Iterable[str]) -> str:
    """Turn a chain list back into the format expected by ProteinMPNN."""

    return " ".join(chains)


def header_value(header: str, key: str) -> Optional[str]:
    """Read a value like score=1.23 from a FASTA header line."""

    # The negative lookbehind prevents key="score" from matching inside
    # "global_score". Values end at a comma or whitespace.
    pattern = rf"(?<![A-Za-z0-9_]){re.escape(key)}=([^,\s]+)"
    match = re.search(pattern, header)
    return match.group(1) if match else None


def header_float(header: str, key: str) -> Optional[float]:
    """Read a float value from a FASTA header if it is present."""

    value = header_value(header, key)
    if value is None:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def header_int(header: str, key: str) -> Optional[int]:
    """Read an integer value from a FASTA header if it is present."""

    value = header_value(header, key)
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def command_as_text(command: list[str]) -> str:
    """Format a subprocess command so it is easy to inspect in the UI."""

    return shlex.join(command)


# ---------------------------------------------------------------------------
# PDB parsing helpers for the preview chart.
# ---------------------------------------------------------------------------


def parse_pdb_summary(pdb_path: Path, selected_chains: list[str]) -> tuple[dict, pd.DataFrame]:
    """Read a tiny summary from a PDB without depending on a biology library.

    The actual model runner does its own proper parsing. This helper is only for
    the app preview: number of residues, chains, and the B-factor/pLDDT trend
    from CA atoms.
    """

    selected = set(selected_chains)
    atom_lines = 0
    chains_seen: set[str] = set()
    residues_seen: set[tuple[str, str, str]] = set()
    ca_by_residue: dict[tuple[str, str, str], dict] = {}
    ca_order = 0

    with pdb_path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            if not line.startswith("ATOM"):
                continue

            # These columns are part of the PDB fixed-width format.
            atom_name = line[12:16].strip()
            altloc = line[16].strip()
            residue_name = line[17:20].strip()
            chain_id = line[21].strip() or "_"
            residue_number = line[22:26].strip()
            insertion_code = line[26].strip()

            # If the user chose chains, the preview focuses on those chains.
            if selected and chain_id not in selected:
                continue

            atom_lines += 1
            chains_seen.add(chain_id)
            residue_key = (chain_id, residue_number, insertion_code)
            residues_seen.add(residue_key)

            # The confidence value we care about is conventionally read from the
            # B-factor column. For AlphaFold this is pLDDT; for X-ray structures
            # it is a crystallographic B-factor.
            if atom_name == "CA":
                try:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])
                    bfactor = float(line[60:66])
                except ValueError:
                    continue

                # Some PDB files contain alternate conformations for the same
                # residue. For a public demo, counting all of them is confusing,
                # so we keep one representative CA atom per residue:
                # blank altloc is best, "A" is next, then anything else.
                altloc_priority = {"": 0, "A": 1}.get(altloc, 2)
                existing = ca_by_residue.get(residue_key)
                if existing is None or altloc_priority < existing["_altloc_priority"]:
                    ca_by_residue[residue_key] = {
                        "order": existing["order"] if existing else ca_order,
                        "_altloc_priority": altloc_priority,
                        "chain": chain_id,
                        "residue": f"{chain_id}{residue_number}{insertion_code}",
                        "residue_name": residue_name,
                        "x": x,
                        "y": y,
                        "z": z,
                        "bfactor_or_plddt": bfactor,
                    }
                    if existing is None:
                        ca_order += 1

    ca_rows = []
    for position, row in enumerate(
        sorted(ca_by_residue.values(), key=lambda item: item["order"]), start=1
    ):
        ca_rows.append(
            {
                "pozicija": position,
                "veriga": row["chain"],
                "ostanek": row["residue"],
                "aminokislina": row["residue_name"],
                "x": row["x"],
                "y": row["y"],
                "z": row["z"],
                "vrednost": row["bfactor_or_plddt"],
            }
        )

    summary = {
        "atom_lines": atom_lines,
        "chains": ", ".join(sorted(chains_seen)) if chains_seen else "none",
        "residue_count": len(residues_seen),
        "ca_count": len(ca_rows),
    }

    return summary, pd.DataFrame(ca_rows)


# ---------------------------------------------------------------------------
# FASTA parsing helpers for model output.
# ---------------------------------------------------------------------------


def read_fasta_records(fasta_path: Path, model_name: str) -> list[DesignedSequence]:
    """Parse the FASTA file written by a ProteinMPNN runner."""

    records: list[DesignedSequence] = []
    current_header: Optional[str] = None
    current_sequence_parts: list[str] = []

    def flush_current_record() -> None:
        """Store the record currently being collected, if there is one."""

        if current_header is None:
            return

        sequence = "".join(current_sequence_parts)
        kind = "design" if current_header.startswith("T=") else "native"

        records.append(
            DesignedSequence(
                model=model_name,
                kind=kind,
                sample=header_int(current_header, "sample"),
                score=header_float(current_header, "score"),
                global_score=header_float(current_header, "global_score"),
                seq_recovery=header_float(current_header, "seq_recovery"),
                header=current_header,
                sequence=sequence,
            )
        )

    with fasta_path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue

            if line.startswith(">"):
                flush_current_record()
                current_header = line[1:]
                current_sequence_parts = []
            else:
                current_sequence_parts.append(line)

    flush_current_record()
    return records


def first_fasta_in_output(output_folder: Path) -> Optional[Path]:
    """Find the first FASTA file generated under <out_folder>/seqs."""

    seq_dir = output_folder / "seqs"
    if not seq_dir.exists():
        return None

    candidates = sorted(seq_dir.glob("*.fa")) + sorted(seq_dir.glob("*.fasta"))
    return candidates[0] if candidates else None


def best_design(records: list[DesignedSequence]) -> Optional[DesignedSequence]:
    """Pick the most useful design for a quick side-by-side comparison."""

    designs = [record for record in records if record.kind == "design"]
    if not designs:
        return None

    # Sequence recovery is the easiest "correctness" number for a demo because
    # it compares the designed sequence to the native PDB sequence. Higher is
    # better. If a runner did not report recovery, fall back to score, where
    # lower is better.
    designs_with_recovery = [record for record in designs if record.seq_recovery is not None]
    if designs_with_recovery:
        return max(designs_with_recovery, key=lambda record: record.seq_recovery or -1.0)

    designs_with_score = [record for record in designs if record.score is not None]
    if designs_with_score:
        return min(designs_with_score, key=lambda record: record.score or float("inf"))

    return designs[0]


def records_to_table(records: list[DesignedSequence]) -> pd.DataFrame:
    """Convert FASTA records into a table for st.dataframe."""

    return pd.DataFrame(
        [
            {
                "Model": record.model,
                "Vrsta": "Predlog" if record.kind == "design" else "Izvirno zaporedje",
                "Vzorec": record.sample,
                "Ujemanje (%)": None
                if record.seq_recovery is None
                else round(record.seq_recovery * 100, 1),
                "Zaporedje": record.sequence,
            }
            for record in records
        ]
    )


# ---------------------------------------------------------------------------
# Model command construction and execution.
# ---------------------------------------------------------------------------


def build_vanilla_command(
    pdb_path: Path,
    output_folder: Path,
    num_sequences: int,
    temperature: str,
    chain_text: str,
) -> list[str]:
    """Build the command for the original ProteinMPNN model."""

    command = [
        sys.executable,
        str(VANILLA_RUNNER),
        "--pdb_path",
        str(pdb_path),
        "--out_folder",
        str(output_folder),
        "--num_seq_per_target",
        str(num_sequences),
        "--batch_size",
        "1",
        "--sampling_temp",
        temperature,
        "--path_to_model_weights",
        str(VANILLA_WEIGHTS),
        "--model_name",
        VANILLA_MODEL_NAME,
        "--seed",
        str(DEMO_SEED),
    ]

    if chain_text:
        command.extend(["--pdb_path_chains", chain_text])

    return command


def build_plddt_command(
    pdb_path: Path,
    output_folder: Path,
    num_sequences: int,
    temperature: str,
    chain_text: str,
    data_source: str,
) -> list[str]:
    """Build the command for the trained pLDDT-weighted model."""

    command = [
        sys.executable,
        str(PLDDT_RUNNER),
        "--pdb_path",
        str(pdb_path),
        "--out_folder",
        str(output_folder),
        "--num_seq_per_target",
        str(num_sequences),
        "--batch_size",
        "1",
        "--sampling_temp",
        temperature,
        "--path_to_model_weights",
        str(PLDDT_WEIGHTS),
        "--model_name",
        PLDDT_MODEL_NAME,
        "--data_source",
        data_source,
        "--seed",
        str(DEMO_SEED),
    ]

    if chain_text:
        command.extend(["--pdb_path_chains", chain_text])

    return command


def run_model_command(model_name: str, command: list[str], output_folder: Path) -> ModelRun:
    """Run one model command and parse its FASTA output."""

    start = time.perf_counter()

    try:
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            text=True,
            capture_output=True,
            timeout=COMMAND_TIMEOUT_SECONDS,
            check=False,
        )
        return_code = completed.returncode
        stdout = completed.stdout
        stderr = completed.stderr
    except subprocess.TimeoutExpired as exc:
        return_code = -1
        stdout = exc.stdout or ""
        stderr = (exc.stderr or "") + f"\nTimed out after {COMMAND_TIMEOUT_SECONDS} seconds."

    elapsed = time.perf_counter() - start
    fasta_path = first_fasta_in_output(output_folder)
    records = read_fasta_records(fasta_path, model_name) if fasta_path else []

    return ModelRun(
        model=model_name,
        return_code=return_code,
        elapsed_seconds=elapsed,
        command=command,
        output_folder=output_folder,
        fasta_path=fasta_path,
        records=records,
        stdout=stdout,
        stderr=stderr,
    )


def save_uploaded_pdb(uploaded_file) -> Path:
    """Save an uploaded Streamlit file to outputs/streamlit_demo/uploads."""

    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = uuid.uuid4().hex[:8]
    file_name = safe_file_name(uploaded_file.name)
    target = UPLOAD_DIR / f"{stamp}_{unique}_{file_name}"

    target.write_bytes(uploaded_file.getbuffer())
    return target


def path_from_text(text: str) -> Path:
    """Resolve a path typed in the sidebar.

    Absolute paths are used as-is. Relative paths are interpreted relative to
    the repository root, which is friendlier when the user types something like
    demo_cases/AF-P15502-F1.pdb.
    """

    path = Path(text).expanduser()
    return path if path.is_absolute() else REPO_ROOT / path


def make_run_root(pdb_path: Path) -> Path:
    """Create a unique output folder for one comparison run."""

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = uuid.uuid4().hex[:8]
    run_root = RUN_DIR / f"{pdb_path.stem}_{stamp}_{unique}"
    run_root.mkdir(parents=True, exist_ok=True)
    return run_root


# ---------------------------------------------------------------------------
# Presentation helpers.
# ---------------------------------------------------------------------------


DATA_SOURCE_LABELS = {
    "AlphaFold: pLDDT v B-factor stolpcu": "alphafold",
    "Eksperimentalni PDB: B-factor": "xray",
    "Samodejno prepoznaj": "auto",
}

CONFIDENCE_BINS = [
    ("<50: zelo nizko zaupanje", 0.0, 50.0),
    ("50-70: nizko zaupanje", 50.0, 70.0),
    ("70-90: dobro zaupanje", 70.0, 90.0),
    (">90: zelo visoko zaupanje", 90.0, float("inf")),
]

# The colors follow the common AlphaFold/pLDDT intuition: warm colors mean less
# confidence, and blue means more confidence. For experimental PDB files we use
# the same colors for a relative confidence signal derived from B-factors.
CONFIDENCE_COLOR_SCALE = [
    [0.0, "#D55E00"],
    [0.499, "#D55E00"],
    [0.5, "#E6AB02"],
    [0.699, "#E6AB02"],
    [0.7, "#56B4E9"],
    [0.899, "#56B4E9"],
    [0.9, "#0072B2"],
    [1.0, "#0072B2"],
]


def percent_text(value: Optional[float]) -> str:
    """Format a 0-1 recovery value as a friendly percentage."""

    return "ni podatka" if value is None else f"{value * 100:.1f} %"


def confidence_copy(data_source: str) -> tuple[str, str, str]:
    """Return title, y-axis label, and explanation for the structure chart."""

    if data_source == "alphafold":
        return (
            "Zaupanje v strukturo po pozicijah",
            "pLDDT",
            "Pri AlphaFold strukturah je v B-factor stolpcu shranjen pLDDT. Višja vrednost pomeni večje zaupanje v napovedano lego tega dela proteina. To ni verjetnost zaporedja, ampak ocena zanesljivosti strukture.",
        )

    if data_source == "xray":
        return (
            "B-factor po pozicijah",
            "B-factor",
            "Pri eksperimentalnih PDB strukturah B-factor opisuje gibljivost oziroma negotovost atoma. Nižja vrednost navadno pomeni bolj zanesljiv del strukture. To ni verjetnost; graf nam pove, kateri deli strukture so bolj stabilni in kateri bolj negotovi.",
        )

    return (
        "Signal iz B-factor stolpca po pozicijah",
        "B-factor / pLDDT",
        "Aplikacija samodejno ugiba, ali B-factor stolpec pomeni AlphaFold pLDDT ali eksperimentalni B-factor. To ni verjetnost zaporedja. Če gre za AlphaFold, višje pomeni bolj zanesljivo strukturo; če gre za eksperimentalni PDB, nižje B-factor vrednosti navadno pomenijo bolj zanesljiv del strukture.",
    )


def confidence_chart(confidence_table: pd.DataFrame, y_title: str) -> alt.Chart:
    """Create a readable line chart for confidence/B-factor values."""

    return (
        alt.Chart(confidence_table)
        .mark_line(point=False, color="#4FA3D1", strokeWidth=2)
        .encode(
            x=alt.X("pozicija:Q", title="Pozicija v proteinskem zaporedju"),
            y=alt.Y("vrednost:Q", title=y_title),
            tooltip=[
                alt.Tooltip("pozicija:Q", title="Pozicija"),
                alt.Tooltip("veriga:N", title="Veriga"),
                alt.Tooltip("ostanek:N", title="Ostanek"),
                alt.Tooltip("aminokislina:N", title="Aminokislina"),
                alt.Tooltip("vrednost:Q", title=y_title, format=".2f"),
            ],
        )
        .properties(height=280)
    )


def normalized_sequence(sequence: str) -> str:
    """Remove separators such as '/' so sequences align with PDB positions."""

    return "".join(character for character in sequence if character.isalpha())


def native_record(records: list[DesignedSequence]) -> Optional[DesignedSequence]:
    """Return the native FASTA record if a model runner wrote one."""

    return next((record for record in records if record.kind == "native"), None)


def confidence_for_bins(confidence_table: pd.DataFrame, data_source: str) -> pd.Series:
    """Return a 0-100 confidence-like value for binning.

    AlphaFold files already store pLDDT on a 0-100 scale. Experimental PDB files
    store B-factors instead, so for display we convert them into a relative
    confidence signal: lower B-factor becomes higher confidence.
    """

    values = confidence_table["vrednost"].astype(float)
    if data_source != "xray":
        return values

    min_value = values.min()
    max_value = values.max()
    if max_value == min_value:
        return pd.Series([100.0] * len(values), index=values.index)

    return 100.0 * (max_value - values) / (max_value - min_value)


def structure_3d_explanation(data_source: str) -> str:
    """Explain what the 3D structure colors mean."""

    if data_source == "xray":
        return (
            "To je poenostavljen 3D prikaz proteinske hrbtenice: vsaka točka je CA atom enega aminokislinskega ostanka, črta pa povezuje zaporedne ostanke. Ker eksperimentalni PDB nima pLDDT, barve pomenijo relativno zanesljivost iz B-factorja: nižji B-factor je prikazan kot bolj zanesljiv del strukture. To ni uradna pLDDT ocena."
        )

    return (
        "To je poenostavljen 3D prikaz proteinske hrbtenice: vsaka točka je CA atom enega aminokislinskega ostanka, črta pa povezuje zaporedne ostanke. Barve kažejo pLDDT, torej zaupanje AlphaFold modela v lego posameznega dela strukture. pLDDT ni ocena pravilnosti zaporedja, ampak ocena zanesljivosti 3D strukture."
    )


def structure_3d_chart(
    confidence_table: pd.DataFrame, data_source: str
):
    """Create an interactive 3D CA-backbone chart colored by confidence."""

    if go is None:
        return None

    required_columns = {"x", "y", "z", "pozicija", "veriga", "ostanek", "aminokislina", "vrednost"}
    if confidence_table.empty or not required_columns.issubset(confidence_table.columns):
        return None

    structure_table = confidence_table.dropna(subset=["x", "y", "z"]).copy()
    if len(structure_table) < 2:
        return None

    structure_table["barvna_vrednost"] = confidence_for_bins(
        structure_table, data_source
    )

    if data_source == "xray":
        colorbar_title = "Relativna zanesljivost"
        hover_template = (
            "<b>Pozicija %{customdata[0]}</b><br>"
            "Veriga: %{customdata[1]}<br>"
            "Ostanek: %{customdata[2]} %{customdata[3]}<br>"
            "B-factor: %{customdata[4]:.2f}<br>"
            "Relativna zanesljivost: %{customdata[5]:.1f}<extra></extra>"
        )
    else:
        colorbar_title = "pLDDT"
        hover_template = (
            "<b>Pozicija %{customdata[0]}</b><br>"
            "Veriga: %{customdata[1]}<br>"
            "Ostanek: %{customdata[2]} %{customdata[3]}<br>"
            "pLDDT: %{customdata[4]:.1f}<extra></extra>"
        )

    figure = go.Figure()

    # Draw one backbone line per chain. This prevents a visual jump between the
    # end of chain A and the start of chain B in multi-chain structures.
    for _, chain_table in structure_table.groupby("veriga", sort=False):
        figure.add_trace(
            go.Scatter3d(
                x=chain_table["x"],
                y=chain_table["y"],
                z=chain_table["z"],
                mode="lines",
                line={"color": "rgba(230, 230, 230, 0.35)", "width": 5},
                hoverinfo="skip",
                showlegend=False,
            )
        )

    figure.add_trace(
        go.Scatter3d(
            x=structure_table["x"],
            y=structure_table["y"],
            z=structure_table["z"],
            mode="markers",
            marker={
                "size": 4,
                "color": structure_table["barvna_vrednost"],
                "cmin": 0,
                "cmax": 100,
                "colorscale": CONFIDENCE_COLOR_SCALE,
                "colorbar": {
                    "title": colorbar_title,
                    "tickmode": "array",
                    "tickvals": [25, 60, 80, 95],
                    "ticktext": ["<50", "50-70", "70-90", ">90"],
                },
            },
            customdata=structure_table[
                ["pozicija", "veriga", "ostanek", "aminokislina", "vrednost", "barvna_vrednost"]
            ],
            hovertemplate=hover_template,
            showlegend=False,
        )
    )

    figure.update_layout(
        height=520,
        margin={"l": 0, "r": 0, "t": 8, "b": 0},
        paper_bgcolor="rgba(0, 0, 0, 0)",
        scene={
            "aspectmode": "data",
            "xaxis": {"visible": False, "showbackground": False},
            "yaxis": {"visible": False, "showbackground": False},
            "zaxis": {"visible": False, "showbackground": False},
            "camera": {"eye": {"x": 1.6, "y": 1.35, "z": 0.9}},
        },
    )

    return figure


def bin_analysis_explanation(data_source: str) -> str:
    """Explain what the confidence bins mean for the current input type."""

    if data_source == "xray":
        return (
            "Pri eksperimentalnem PDB-ju nimamo pravega pLDDT. Zato za ta prikaz B-factor obrnemo v približno relativno zanesljivost: nižji B-factor pomeni višji razred zanesljivosti. Graf je uporaben kot intuicija, ne kot uradna pLDDT meritev."
        )

    return (
        "Razredi so narejeni iz pLDDT vrednosti: pod 50 pomeni zelo nezanesljiv del strukture, 50-70 nizko zaupanje, 70-90 dobro zaupanje, nad 90 pa zelo visoko zaupanje. Če je modra vrstica višja v nizkih razredih, to pomeni, da uteži zanesljivosti pomagajo prav tam, kjer je struktura manj gotova."
    )


def per_bin_recovery_rows(
    native: Optional[DesignedSequence],
    design: Optional[DesignedSequence],
    model_label: str,
    confidence_table: pd.DataFrame,
    data_source: str,
) -> list[dict]:
    """Compute sequence recovery inside each confidence bin."""

    if native is None or design is None or confidence_table.empty:
        return []

    native_sequence = normalized_sequence(native.sequence)
    design_sequence = normalized_sequence(design.sequence)
    confidence_values = list(confidence_for_bins(confidence_table, data_source))
    usable_length = min(len(native_sequence), len(design_sequence), len(confidence_values))
    if usable_length == 0:
        return []

    rows = []
    for label, low, high in CONFIDENCE_BINS:
        indices = [
            index
            for index, value in enumerate(confidence_values[:usable_length])
            if low <= value < high
        ]
        if not indices:
            continue

        matches = sum(
            1 for index in indices if native_sequence[index] == design_sequence[index]
        )
        rows.append(
            {
                "Razred zanesljivosti": label,
                "Model": model_label,
                "Pozicije": len(indices),
                "Ujemanje (%)": 100.0 * matches / len(indices),
            }
        )

    return rows


def bin_recovery_chart(table: pd.DataFrame) -> alt.Chart:
    """Create a grouped bar chart for per-bin sequence recovery."""

    bin_order = [label for label, _, _ in CONFIDENCE_BINS]
    return (
        alt.Chart(table)
        .mark_bar(cornerRadiusEnd=4)
        .encode(
            y=alt.Y(
                "Razred zanesljivosti:N",
                sort=bin_order,
                title=None,
                axis=alt.Axis(labelLimit=260, labelPadding=8),
            ),
            yOffset=alt.YOffset("Model:N", sort=[BASELINE_LABEL, PLDDT_LABEL]),
            x=alt.X(
                "Ujemanje (%):Q",
                title="Ujemanje z znanim zaporedjem (%)",
                scale=alt.Scale(domain=[0, 100]),
            ),
            color=alt.Color(
                "Model:N",
                legend=alt.Legend(title="Model"),
                scale=alt.Scale(range=["#7BC96F", "#4FA3D1"]),
            ),
            tooltip=[
                alt.Tooltip("Razred zanesljivosti:N", title="Razred"),
                alt.Tooltip("Model:N", title="Model"),
                alt.Tooltip("Pozicije:Q", title="Število pozicij"),
                alt.Tooltip("Ujemanje (%):Q", title="Ujemanje", format=".1f"),
            ],
        )
        .properties(height=260)
    )


def result_bar_chart(table: pd.DataFrame, value_column: str, x_title: str) -> alt.Chart:
    """Create a horizontal bar chart with labels that do not get cut off."""

    return (
        alt.Chart(table)
        .mark_bar(cornerRadiusEnd=4, height=32)
        .encode(
            y=alt.Y(
                "Model:N",
                sort=None,
                title=None,
                axis=alt.Axis(labelLimit=260, labelPadding=8),
            ),
            x=alt.X(f"{value_column}:Q", title=x_title),
            color=alt.Color(
                "Model:N",
                legend=None,
                scale=alt.Scale(range=["#4FA3D1", "#7BC96F"]),
            ),
            tooltip=[
                alt.Tooltip("Model:N", title="Model"),
                alt.Tooltip(f"{value_column}:Q", title=x_title, format=".3f"),
            ],
        )
        .properties(height=140)
    )


def comparison_sentence(
    baseline: Optional[DesignedSequence], plddt: Optional[DesignedSequence]
) -> str:
    """Summarize which model did better on sequence recovery."""

    if baseline is None or plddt is None:
        return "Primerjava ni popolna, ker eden od modelov ni vrnil predloga."

    if baseline.seq_recovery is None or plddt.seq_recovery is None:
        return "Modela sta vrnila zaporedja, vendar v izhodu ni bilo podatka o ujemanju."

    difference = (plddt.seq_recovery - baseline.seq_recovery) * 100
    if difference > 0:
        return f"Na tem primeru je model z utežmi zanesljivosti dosegel za {difference:.1f} odstotne točke boljše ujemanje z izvirnim zaporedjem."
    if difference < 0:
        return f"Na tem primeru je osnovni model dosegel za {abs(difference):.1f} odstotne točke boljše ujemanje. To je še vedno uporaben rezultat, ker vidimo, kje pristop z utežmi zanesljivosti pomaga in kje ne."
    return "Na tem primeru sta modela dosegla enako ujemanje z izvirnim zaporedjem."


# ---------------------------------------------------------------------------
# Streamlit rendering helpers.
# ---------------------------------------------------------------------------


def render_best_design_card(title: str, record: Optional[DesignedSequence]) -> None:
    """Show the best sequence from one model in a compact block."""

    st.subheader(title)
    if record is None:
        st.warning("Ta model ni vrnil predloga zaporedja.")
        return

    st.metric("Ujemanje z znanim zaporedjem", percent_text(record.seq_recovery))
    st.caption(
        "To pove, kolikšen delež aminokislin v predlogu je enak izvirnemu zaporedju iz PDB datoteke. Višje je boljše, vendar to ni popoln dokaz biološke pravilnosti."
    )

    with st.expander("Prikaži najboljši predlog zaporedja"):
        st.write(
            "To je zaporedje aminokislin, ki ga je model predlagal za izbrano 3D strukturo. Vsaka črka pomeni eno aminokislino. Zaporedje samo po sebi ni verjetnost; za interpretacijo uporabljamo ujemanje z znanim zaporedjem in analizo po razredih zanesljivosti."
        )
        st.code(record.sequence, language="text")


def render_run_debug(run: ModelRun) -> None:
    """Show command and logs in an expander so they do not clutter the page."""

    status = "končano" if run.ok else f"napaka, izhodna koda {run.return_code}"
    with st.expander(f"Tehnične podrobnosti: {run.model} ({status})"):
        st.write("Ukaz")
        st.code(command_as_text(run.command), language="bash")

        st.write("Mapa z izhodnimi datotekami")
        st.code(str(run.output_folder), language="text")

        if run.fasta_path:
            st.write("Prebrana FASTA datoteka")
            st.code(str(run.fasta_path), language="text")

        if run.stdout:
            st.write("stdout")
            st.code(run.stdout, language="text")

        if run.stderr:
            st.write("stderr")
            st.code(run.stderr, language="text")


# ---------------------------------------------------------------------------
# Main Streamlit app.
# ---------------------------------------------------------------------------


st.set_page_config(
    page_title="Primerjava proteinskih modelov",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Hide Streamlit's developer-oriented chrome as much as possible. The "Deploy"
# button belongs to Streamlit, not to our app; this CSS makes the demo cleaner
# for a non-technical audience.
st.markdown(
    """
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    [data-testid="stToolbar"] {visibility: hidden; height: 0; position: fixed;}
    .stDeployButton {display: none;}
    .stCodeBlock pre {white-space: pre-wrap;}
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("Primerjava oblikovanja proteinskih zaporedij")
st.write(
    "Aplikacija vzame 3D strukturo proteina in primerja dva pristopa za predlaganje aminokislinskega zaporedja."
)

# Keep the latest completed run in Streamlit's session state. Streamlit reruns
# the script after every click, so session_state is how we remember results.
if "last_runs" not in st.session_state:
    st.session_state.last_runs = None
if "uploaded_pdb_key" not in st.session_state:
    st.session_state.uploaded_pdb_key = None
if "uploaded_pdb_path" not in st.session_state:
    st.session_state.uploaded_pdb_path = None


with st.sidebar:
    st.header("1. Vhodna struktura")

    input_mode = st.radio(
        "Od kod vzamemo PDB datoteko?",
        ["Primeri za predstavitev", "Naloži PDB datoteko", "Pot do lokalne datoteke"],
        help="PDB datoteka vsebuje 3D strukturo proteina. Model iz nje prebere proteinsko hrbtenico.",
    )

    uploaded_pdb = None
    local_pdb_text = str(DEFAULT_PDB)
    demo_case_label = next(iter(DEMO_CASES.keys()))

    if input_mode == "Primeri za predstavitev":
        demo_case_label = st.selectbox(
            "Izberi predstavitveni primer",
            list(DEMO_CASES.keys()),
            help="To so primeri, kjer je model z utežmi zanesljivosti v hitrem testu premagal osnovni model.",
        )
    elif input_mode == "Naloži PDB datoteko":
        uploaded_pdb = st.file_uploader("PDB datoteka", type=["pdb", "ent", "txt"])
    elif input_mode == "Pot do lokalne datoteke":
        local_pdb_text = st.text_input("Pot do PDB datoteke", value=str(DEFAULT_PDB))

    recommended_source_label = DEMO_CASE_DATA_SOURCE.get(
        demo_case_label,
        "AlphaFold: pLDDT v B-factor stolpcu",
    )
    source_labels = list(DATA_SOURCE_LABELS.keys())
    source_index = (
        source_labels.index(recommended_source_label)
        if recommended_source_label in source_labels
        else 0
    )

    data_source_label = st.selectbox(
        "Kaj pomeni B-factor stolpec?",
        source_labels,
        index=source_index,
        key=f"data_source_{input_mode}_{demo_case_label}",
        help="AlphaFold v ta stolpec zapiše pLDDT. Eksperimentalne strukture pa imajo običajen B-factor.",
    )
    data_source = DATA_SOURCE_LABELS[data_source_label]

    chain_text_raw = st.text_input(
        "Katere verige naj oblikujemo?",
        value="",
        help="Pustite prazno za vse verige. Primer: A ali A B. Pri večjih strukturah je za hiter demo bolje izbrati samo eno verigo.",
    )
    selected_chains = chain_list_from_text(chain_text_raw)
    cli_chain_text = chain_text_for_cli(selected_chains)

    st.header("2. Nastavitve zagona")
    st.caption(
        "Več predlogov pomeni počasnejši izračun. Za hitro predstavitev začnite z 1 ali 2 predlogoma."
    )
    num_sequences = st.slider("Število predlogov na model", min_value=1, max_value=8, value=2)
    temperature = st.text_input(
        "Raznolikost predlogov",
        value="0.1",
        help="Nižja vrednost naredi bolj konservativne predloge. Višja vrednost naredi bolj raznolike predloge.",
    )

    run_button = st.button("Zaženi primerjavo", type="primary")


# Resolve the PDB input after the sidebar widgets have been read.
if input_mode == "Naloži PDB datoteko" and uploaded_pdb is not None:
    # Streamlit reruns this file whenever the user changes a widget. The key
    # below prevents us from saving the same upload again on every rerun.
    upload_key = f"{uploaded_pdb.name}:{uploaded_pdb.size}"
    if st.session_state.uploaded_pdb_key != upload_key:
        st.session_state.uploaded_pdb_path = save_uploaded_pdb(uploaded_pdb)
        st.session_state.uploaded_pdb_key = upload_key
    pdb_path = Path(st.session_state.uploaded_pdb_path)
elif input_mode == "Pot do lokalne datoteke":
    pdb_path = path_from_text(local_pdb_text)
else:
    pdb_path = DEMO_CASES[demo_case_label]


if not pdb_path.exists():
    st.error("Izbrana PDB datoteka ne obstaja.")
    st.stop()


# Show a lightweight preview before any model is launched.
pdb_summary, confidence_table = parse_pdb_summary(pdb_path, selected_chains)

st.header("1. Vhodni protein")
st.write(
    f"Uporabljena struktura: **{pdb_path.name}**. Model bo iz nje prebral proteinsko hrbtenico in poskusil predlagati ustrezno zaporedje aminokislin."
)
with st.expander("Prikaži pot do datoteke"):
    st.code(str(pdb_path), language="text")

st.subheader("Kaj je v datoteki?")
st.caption(
    "Te številke nam povedo, kako velika je struktura. Več ostankov in več verig običajno pomeni daljši izračun."
)
metric_a, metric_b, metric_c, metric_d = st.columns(4)
metric_a.metric("Atomi", pdb_summary["atom_lines"])
metric_b.metric("Aminokislinski ostanki", pdb_summary["residue_count"])
metric_c.metric("Pozicije v grafu", pdb_summary["ca_count"])
metric_d.metric("Verige", pdb_summary["chains"])

if not confidence_table.empty:
    chart_title, chart_y_title, chart_explanation = confidence_copy(data_source)
    st.subheader(chart_title)
    st.write(chart_explanation)
    st.altair_chart(
        confidence_chart(confidence_table, chart_y_title),
        use_container_width=True,
    )

    st.subheader("3D prikaz strukture in zanesljivosti")
    st.write(structure_3d_explanation(data_source))
    if go is None:
        st.info(
            "Za 3D prikaz manjka knjižnica Plotly. Namestite odvisnosti iz streamlit_demo/requirements.txt in ponovno zaženite aplikacijo."
        )
    else:
        structure_chart = structure_3d_chart(confidence_table, data_source)
        if structure_chart is None:
            st.info(
                "3D prikaza ni bilo mogoče sestaviti, ker v izbranem delu PDB datoteke ni dovolj CA koordinat."
            )
        else:
            st.plotly_chart(structure_chart, use_container_width=True)
            st.caption(
                "Barve: oranžno = zelo nizko zaupanje (<50), rumeno = nizko zaupanje (50-70), svetlo modro = dobro zaupanje (70-90), temno modro = zelo visoko zaupanje (>90). Graf lahko z miško zavrtite in povečate."
            )
else:
    st.warning("Za izbrane verige ni bilo mogoče najti CA vrednosti za graf.")


if run_button:
    run_root = make_run_root(pdb_path)
    vanilla_out = run_root / "vanilla"
    plddt_out = run_root / "plddt_weighted"

    vanilla_command = build_vanilla_command(
        pdb_path=pdb_path,
        output_folder=vanilla_out,
        num_sequences=num_sequences,
        temperature=temperature,
        chain_text=cli_chain_text,
    )
    plddt_command = build_plddt_command(
        pdb_path=pdb_path,
        output_folder=plddt_out,
        num_sequences=num_sequences,
        temperature=temperature,
        chain_text=cli_chain_text,
        data_source=data_source,
    )

    # Run the models one after the other. This is simpler and easier to debug
    # than parallel execution for a first Streamlit app.
    st.divider()
    st.header("2. Izračun v teku")
    st.warning(
        "To lahko traja nekaj minut, še posebej pri večjih strukturah ali večjem številu predlogov. Aplikacije medtem ne zapirajte."
    )

    progress = st.progress(0, text="Pripravljam primerjavo...")
    status_box = st.status("Modela računata predloge zaporedij.", expanded=True)
    with status_box:
        st.write("1/2: Računam z osnovnim modelom.")
        progress.progress(10, text="Računam z osnovnim modelom...")
        vanilla_run = run_model_command(BASELINE_LABEL, vanilla_command, vanilla_out)

        st.write("2/2: Računam z modelom z utežmi zanesljivosti.")
        progress.progress(55, text="Računam z modelom z utežmi zanesljivosti...")
        plddt_run = run_model_command(PLDDT_LABEL, plddt_command, plddt_out)

        progress.progress(100, text="Primerjava je končana.")
        st.write("Končano.")
    status_box.update(label="Primerjava je končana.", state="complete", expanded=False)

    st.session_state.last_runs = {
        "run_root": run_root,
        "vanilla": vanilla_run,
        "plddt": plddt_run,
        "confidence_table": confidence_table.copy(),
        "data_source": data_source,
    }


if st.session_state.last_runs is not None:
    run_root = st.session_state.last_runs["run_root"]
    vanilla_run = st.session_state.last_runs["vanilla"]
    plddt_run = st.session_state.last_runs["plddt"]
    run_confidence_table = st.session_state.last_runs.get(
        "confidence_table", confidence_table
    )
    run_data_source = st.session_state.last_runs.get("data_source", data_source)

    st.divider()
    st.header("2. Rezultati primerjave")
    st.write(
        "Oba modela sta dobila isto proteinsko strukturo. Primerjamo, kateri model je predlagal zaporedje, ki je bolj podobno znanemu zaporedju iz PDB datoteke."
    )

    vanilla_best = best_design(vanilla_run.records)
    plddt_best = best_design(plddt_run.records)

    if vanilla_run.ok and plddt_run.ok:
        st.success(comparison_sentence(vanilla_best, plddt_best))
    else:
        st.error(
            "Eden od zagonov se ni zaključil pravilno. Odprite tehnične podrobnosti na dnu strani."
        )

    duration = vanilla_run.elapsed_seconds + plddt_run.elapsed_seconds
    st.metric("Čas izračuna", f"{duration:.1f} s")

    best_left, best_right = st.columns(2)
    with best_left:
        render_best_design_card(BASELINE_LABEL, vanilla_best)
    with best_right:
        render_best_design_card(PLDDT_LABEL, plddt_best)

    best_rows = []
    for record in [vanilla_best, plddt_best]:
        if record is None:
            continue
        best_rows.append(
            {
                "Model": record.model,
                "Vzorec": record.sample,
                "Ujemanje z znanim zaporedjem (%)": None
                if record.seq_recovery is None
                else record.seq_recovery * 100,
            }
        )

    if best_rows:
        best_table = pd.DataFrame(best_rows)
        st.subheader("Ujemanje z znanim zaporedjem")
        st.write(
            "Ta graf pove, kolikšen delež aminokislin je enak izvirnemu zaporedju v PDB datoteki. Višje je boljše."
        )
        if best_table["Ujemanje z znanim zaporedjem (%)"].notna().any():
            st.altair_chart(
                result_bar_chart(
                    best_table,
                    "Ujemanje z znanim zaporedjem (%)",
                    "Ujemanje (%)",
                ),
                use_container_width=True,
            )
        else:
            st.info("Modela nista zapisala vrednosti za ujemanje.")

    bin_rows = []
    baseline_native = native_record(vanilla_run.records)
    weighted_native = native_record(plddt_run.records) or baseline_native
    bin_rows.extend(
        per_bin_recovery_rows(
            baseline_native,
            vanilla_best,
            BASELINE_LABEL,
            run_confidence_table,
            run_data_source,
        )
    )
    bin_rows.extend(
        per_bin_recovery_rows(
            weighted_native,
            plddt_best,
            PLDDT_LABEL,
            run_confidence_table,
            run_data_source,
        )
    )

    st.subheader("Ujemanje po razredih zanesljivosti")
    st.write(bin_analysis_explanation(run_data_source))
    if bin_rows:
        bin_table = pd.DataFrame(bin_rows)
        st.altair_chart(bin_recovery_chart(bin_table), use_container_width=True)
        with st.expander("Prikaži številke za razrede zanesljivosti"):
            st.dataframe(
                bin_table.round({"Ujemanje (%)": 1}),
                use_container_width=True,
            )
    else:
        st.info(
            "Analize po razredih zanesljivosti ni bilo mogoče izračunati za ta zagon."
        )

    all_records = vanilla_run.records + plddt_run.records
    if all_records:
        with st.expander("Prikaži vse generirane predloge"):
            st.write(
                "Ta tabela je namenjena podrobnejšemu ogledu. Za predstavitev je najpomembnejša vrstica 'Predlog' z najboljšim ujemanjem."
            )
            st.dataframe(records_to_table(all_records), use_container_width=True)

    with st.expander("Tehnični povzetek za preverjanje"):
        st.caption(
            "To je skrito zato, ker je namenjeno nam za razhroščevanje, ne komisiji."
        )
        st.write(f"Mapa zagona: {run_root}")
        st.write(f"Osnovni model: {VANILLA_MODEL_NAME}")
        st.write(f"Model z utežmi zanesljivosti: {PLDDT_MODEL_NAME}")
        st.write(f"Izhodna koda osnovnega modela: {vanilla_run.return_code}")
        st.write(f"Izhodna koda modela z utežmi zanesljivosti: {plddt_run.return_code}")

    render_run_debug(vanilla_run)
    render_run_debug(plddt_run)
